const ADMIN_TEXT_MAP = {
  en: {
    'Admin Console': 'Admin Console',
    'Admin Workspace': 'Admin Workspace',
    'Welcome back,': 'Welcome back,',
    'Manage the entire institution with a cleaner workspace and faster navigation.': 'Manage the entire institution with a cleaner workspace and faster navigation.',
    'Search modules, users, reports...': 'Search modules, users, reports...',
    Overview: 'Overview',
    Operations: 'Operations',
    Management: 'Management',
    Dashboard: 'Dashboard',
    'User Management': 'User Management',
    'All Users': 'All Users',
    Students: 'Students',
    Teachers: 'Teachers',
    Staff: 'Staff',
    'Register New User': 'Register New User',
    'Roles & Permissions': 'Roles & Permissions',
    'Audit Logs': 'Audit Logs',
    Academic: 'Academic',
    Classes: 'Classes',
    Subjects: 'Subjects',
    Exams: 'Exams',
    Timetable: 'Timetable',
    Degrees: 'Degrees',
    Syllabus: 'Syllabus',
    'Grading System': 'Grading System',
    Attendance: 'Attendance',
    'Daily Attendance': 'Daily Attendance',
    Reports: 'Reports',
    Settings: 'Settings',
    'Attendance Warnings': 'Attendance Warnings',
    Corrections: 'Corrections',
    Finance: 'Finance',
    'Fee Structure': 'Fee Structure',
    Payments: 'Payments',
    Expenses: 'Expenses',
    Salaries: 'Salaries',
    Accounts: 'Accounts',
    Transactions: 'Transactions',
    'Financial Reports': 'Financial Reports',
    Library: 'Library',
    Books: 'Books',
    Categories: 'Categories',
    'Borrowed Books': 'Borrowed Books',
    Purchases: 'Purchases',
    Sales: 'Sales',
    Complaints: 'Complaints',
    'All Complaints': 'All Complaints',
    Pending: 'Pending',
    Resolved: 'Resolved',
    Actions: 'Actions',
    Feedback: 'Feedback',
    Hostel: 'Hostel',
    Rooms: 'Rooms',
    Allocations: 'Allocations',
    Meals: 'Meals',
    'Meal Attendance': 'Meal Attendance',
    'HR Management': 'HR Management',
    Departments: 'Departments',
    Designations: 'Designations',
    Employees: 'Employees',
    'Employee Attendance': 'Employee Attendance',
    'Leave Management': 'Leave Management',
    Payroll: 'Payroll',
    'HR Reports': 'HR Reports',
    Kitchen: 'Kitchen',
    Inventory: 'Inventory',
    'Meal Planning': 'Meal Planning',
    'Weekly Menu': 'Weekly Menu',
    Suppliers: 'Suppliers',
    'Waste Tracking': 'Waste Tracking',
    'Analytics Dashboard': 'Analytics Dashboard',
    'System Settings': 'System Settings',
    'General Settings': 'General Settings',
    'Academic Settings': 'Academic Settings',
    Notifications: 'Notifications',
    Security: 'Security',
    'Backup & Restore': 'Backup & Restore',
    'API Management': 'API Management',
    Profile: 'Profile',
    'Account and identity': 'Account and identity',
    Logout: 'Logout',
    'Exit this workspace': 'Exit this workspace',
    'Toggle theme': 'Toggle theme',
    Language: 'Language',
    'Collapse sidebar': 'Collapse sidebar',
    'Expand sidebar': 'Expand sidebar',
    'Madrasa Info': 'Madrasa Info',
    Loading: 'Loading',
    'Loading...': 'Loading...',
    Search: 'Search',
    'Search...': 'Search...',
    'Search And Filter': 'Search And Filter',
    'Quick controls for finding records faster.': 'Quick controls for finding records faster.',
    'Filter By': 'Filter By',
    'All Columns': 'All Columns',
    'Filter Value': 'Filter Value',
    'Type to filter rows...': 'Type to filter rows...',
    'Records Table': 'Records Table',
    'Unified filtering, sorting, pagination, and row actions.': 'Unified filtering, sorting, pagination, and row actions.',
    'No Records': 'No Records',
    'Nothing matches your current filters': 'Nothing matches your current filters',
    'Try changing the search terms, switching the filter column, or create the first record for this module.': 'Try changing the search terms, switching the filter column, or create the first record for this module.',
    'Unable to Load Data': 'Unable to Load Data',
    Retry: 'Retry',
    'Loading data...': 'Loading data...',
    'Delete this account?': 'Delete this account?',
    'Delete this class?': 'Delete this class?',
    'Delete this subject?': 'Delete this subject?',
    'Delete this record?': 'Delete this record?',
    'Are you sure you want to delete this record?': 'Are you sure you want to delete this record?',
    Cancel: 'Cancel',
    Save: 'Save',
    Create: 'Create',
    Update: 'Update',
    Edit: 'Edit',
    Delete: 'Delete',
    'Add New': 'Add New',
    'Add New Class': 'Add New Class',
    'Add New Subject': 'Add New Subject',
    'Add New User': 'Add New User',
    'View Details': 'View Details',
    View: 'View',
    Back: 'Back',
    Next: 'Next',
    'Next Step': 'Next Step',
    'Save Record': 'Save Record',
    'Create Record': 'Create Record',
    'Confirm Delete': 'Confirm Delete',
    'No records found': 'No records found',
    'More Filters': 'More Filters',
    Export: 'Export',
    'Create First Record': 'Create First Record',
    'Create Flow': 'Create Flow',
    'Edit Flow': 'Edit Flow',
    'No.': 'No.',
    Basics: 'Basics',
    Identity: 'Identity',
    Relations: 'Relations',
    Details: 'Details',
    Review: 'Review',
    'Form Error': 'Form Error',
    'Save error': 'Save error',
    'Please correct the highlighted fields.': 'Please correct the highlighted fields.',
    'Step': 'Step',
    'Manage income and expense transactions with live balance and verification visibility.': 'Manage income and expense transactions with live balance and verification visibility.',
    'Manage account balances, status, and account-type distribution.': 'Manage account balances, status, and account-type distribution.',
    'Manage fee categories, frequencies, and active pricing structure.': 'Manage fee categories, frequencies, and active pricing structure.',
    'Track fee assignments, outstanding balances, and collection risk by status.': 'Track fee assignments, outstanding balances, and collection risk by status.',
    'Manage collection activity, verification queues, and payment channels.': 'Manage collection activity, verification queues, and payment channels.',
    'Review spending, approval workload, and category mix from live expense records.': 'Review spending, approval workload, and category mix from live expense records.',
    'Manage financial report records': 'Manage financial report records',
    'Financial Transactions': 'Financial Transactions',
    'Financial Accounts': 'Financial Accounts',
    'Fee Structure': 'Fee Structure',
    'Student Fees': 'Student Fees',
    'Fee Payments': 'Fee Payments',
    'Expenses': 'Expenses',
    'Date': 'Date',
    'Code': 'Code',
    'Description': 'Description',
    'Type': 'Type',
    'Amount': 'Amount',
    'Status': 'Status',
    'Account Code': 'Account Code',
    'Account Name': 'Account Name',
    'Opening Balance': 'Opening Balance',
    'Current Balance': 'Current Balance',
    'Currency': 'Currency',
    'Fee Code': 'Fee Code',
    'Fee Name': 'Fee Name',
    'Fee Type': 'Fee Type',
    'Frequency': 'Frequency',
    'Mandatory': 'Mandatory',
    'Student': 'Student',
    'Fee Structure ID': 'Fee Structure ID',
    'Academic Year': 'Academic Year',
    'Total Amount': 'Total Amount',
    'Discount': 'Discount',
    'Payable': 'Payable',
    'Student Fee ID': 'Student Fee ID',
    'Receipt No': 'Receipt No',
    'Payment Date': 'Payment Date',
    'Paid Amount': 'Paid Amount',
    'Method': 'Method',
    'Verification': 'Verification',
    'Expense Code': 'Expense Code',
    'Category': 'Category',
    'Title': 'Title',
    'Expense Date': 'Expense Date',
    'Payment Method': 'Payment Method',
    'Approval Status': 'Approval Status',
    'Report Type': 'Report Type',
    'Report Period': 'Report Period',
    'Total Income': 'Total Income',
    'Total Expense': 'Total Expense',
    'Net Balance': 'Net Balance',
    'Transaction Type': 'Transaction Type',
    'Transaction Date': 'Transaction Date',
    'Reference Type': 'Reference Type',
    'Verification Status': 'Verification Status',
    'Account': 'Account',
    'Account Type': 'Account Type',
    'Class': 'Class',
    'Applicable From': 'Applicable From',
    'Applicable To': 'Applicable To',
    'Student Fee': 'Student Fee',
    'Transaction Reference': 'Transaction Reference',
    'Payment Status': 'Payment Status',
    'Payment Channel': 'Payment Channel',
    'Remarks': 'Remarks',
    'Reference No': 'Reference No',
    'Paid To': 'Paid To',
    'Generated At': 'Generated At',
    Income: 'Income',
    Expense: 'Expense',
    Verified: 'Verified',
    Rejected: 'Rejected',
    Cash: 'Cash',
    'Petty Cash': 'Petty Cash',
    Active: 'Active',
    Inactive: 'Inactive',
    Tuition: 'Tuition',
    Admission: 'Admission',
    'One-Time': 'One-Time',
    Monthly: 'Monthly',
    Yearly: 'Yearly',
    Yes: 'Yes',
    No: 'No',
    Paid: 'Paid',
    Partial: 'Partial',
    Overdue: 'Overdue',
    Completed: 'Completed',
    Failed: 'Failed',
    Approved: 'Approved',
    Other: 'Other',
    Card: 'Card',
    'Discount Amount': 'Discount Amount',
    'Payable Amount': 'Payable Amount',
    'Due Date': 'Due Date',
    'Image size must be less than 5MB': 'Image size must be less than 5MB',
    'A phased entry flow keeps create and edit tasks easier to complete without overwhelming the form.': 'A phased entry flow keeps create and edit tasks easier to complete without overwhelming the form.',
    of: 'of',
    'Unknown error': 'Unknown error',
    'Delete failed': 'Delete failed',
    'Delete error': 'Delete error',
    'Save failed': 'Save failed',
  },
  dari: {
    'Admin Console': 'کنسول مدیریت',
    'Admin Workspace': 'فضای کاری مدیریت',
    'Welcome back,': 'خوش آمدید،',
    'Manage the entire institution with a cleaner workspace and faster navigation.': 'کل مؤسسه را با فضای کاری منظم‌تر و ناوبری سریع‌تر مدیریت کنید.',
    'Search modules, users, reports...': 'جستجوی ماژول‌ها، کاربران، گزارش‌ها...',
    Overview: 'مرور کلی',
    Operations: 'عملیات',
    Management: 'مدیریت',
    Dashboard: 'داشبورد',
    'User Management': 'مدیریت کاربران',
    'All Users': 'همه کاربران',
    Students: 'شاگردان',
    Teachers: 'استادان',
    Staff: 'کارمندان',
    'Register New User': 'ثبت کاربر جدید',
    'Roles & Permissions': 'نقش‌ها و مجوزها',
    'Audit Logs': 'لاگ‌های حسابرسی',
    Academic: 'علمی',
    Classes: 'صنف‌ها',
    Subjects: 'مضامین',
    Exams: 'امتحانات',
    Timetable: 'تایم‌تیبل',
    Degrees: 'درجه‌ها',
    Syllabus: 'نصاب تعلیمی',
    'Grading System': 'سیستم نمره‌دهی',
    Attendance: 'حاضری',
    'Daily Attendance': 'حاضری روزانه',
    Reports: 'گزارش‌ها',
    Settings: 'تنظیمات',
    'Attendance Warnings': 'هشدارهای حاضری',
    Corrections: 'اصلاحات',
    Finance: 'مالیه',
    'Fee Structure': 'ساختار فیس',
    Payments: 'پرداخت‌ها',
    Expenses: 'مصارف',
    Salaries: 'معاشات',
    Accounts: 'حساب‌ها',
    Transactions: 'معاملات',
    'Financial Reports': 'گزارش‌های مالی',
    Library: 'کتابخانه',
    Books: 'کتاب‌ها',
    Categories: 'دسته‌بندی‌ها',
    'Borrowed Books': 'کتاب‌های مستعار',
    Purchases: 'خریداری',
    Sales: 'فروش',
    Complaints: 'شکایات',
    'All Complaints': 'همه شکایات',
    Pending: 'معلق',
    Resolved: 'حل‌شده',
    Actions: 'اقدامات',
    Feedback: 'بازخورد',
    Hostel: 'هاستل',
    Rooms: 'اتاق‌ها',
    Allocations: 'تخصیص‌ها',
    Meals: 'وعده‌های غذایی',
    'Meal Attendance': 'حاضری غذا',
    'HR Management': 'منابع بشری',
    Departments: 'دیپارتمنت‌ها',
    Designations: 'رتبه‌ها',
    Employees: 'کارمندان',
    'Employee Attendance': 'حاضری کارمندان',
    'Leave Management': 'مدیریت رخصتی',
    Payroll: 'معاش‌پردازی',
    'HR Reports': 'گزارش‌های منابع بشری',
    Kitchen: 'آشپزخانه',
    Inventory: 'موجودی',
    'Meal Planning': 'برنامه‌ریزی غذا',
    'Weekly Menu': 'منوی هفتگی',
    Suppliers: 'عرضه‌کنندگان',
    'Waste Tracking': 'ردیابی ضایعات',
    'Analytics Dashboard': 'داشبورد تحلیلی',
    'System Settings': 'تنظیمات سیستم',
    'General Settings': 'تنظیمات عمومی',
    'Academic Settings': 'تنظیمات علمی',
    Notifications: 'اعلانات',
    Security: 'امنیت',
    'Backup & Restore': 'پشتیبان‌گیری و بازیابی',
    'API Management': 'مدیریت API',
    Profile: 'پروفایل',
    'Account and identity': 'حساب و هویت',
    Logout: 'خروج',
    'Exit this workspace': 'خروج از فضای کاری',
    'Toggle theme': 'تغییر تم',
    Language: 'زبان',
    'Collapse sidebar': 'جمع کردن نوار کناری',
    'Expand sidebar': 'باز کردن نوار کناری',
    'Madrasa Info': 'اطلاعات مدرسه',
    Loading: 'در حال بارگذاری',
    'Loading...': 'در حال بارگذاری...',
    Search: 'جستجو',
    'Search...': 'جستجو...',
    'Search And Filter': 'جستجو و فیلتر',
    'Quick controls for finding records faster.': 'کنترل‌های سریع برای یافتن رکوردها با سرعت بیشتر.',
    'Filter By': 'فیلتر بر اساس',
    'All Columns': 'همه ستون‌ها',
    'Filter Value': 'مقدار فیلتر',
    'Type to filter rows...': 'برای فیلتر کردن ردیف‌ها تایپ کنید...',
    'Records Table': 'جدول رکوردها',
    'Unified filtering, sorting, pagination, and row actions.': 'فیلتر، مرتب‌سازی، صفحه‌بندی و عملیات ردیف‌ها به‌صورت یکپارچه.',
    'No Records': 'رکوردی وجود ندارد',
    'Nothing matches your current filters': 'هیچ چیزی با فیلترهای فعلی شما مطابقت ندارد',
    'Try changing the search terms, switching the filter column, or create the first record for this module.': 'کلمات جستجو را تغییر دهید، ستون فیلتر را عوض کنید یا اولین رکورد را برای این ماژول بسازید.',
    'Unable to Load Data': 'بارگذاری داده‌ها ممکن نیست',
    Retry: 'تلاش دوباره',
    'Loading data...': 'در حال بارگذاری داده‌ها...',
    'Delete this account?': 'این حساب حذف شود؟',
    'Delete this class?': 'این صنف حذف شود؟',
    'Delete this subject?': 'این مضمون حذف شود؟',
    'Delete this record?': 'این رکورد حذف شود؟',
    'Are you sure you want to delete this record?': 'آیا مطمئن هستید که می‌خواهید این رکورد را حذف کنید؟',
    Cancel: 'لغو',
    Save: 'ذخیره',
    Create: 'ایجاد',
    Update: 'به‌روزرسانی',
    Edit: 'ویرایش',
    Delete: 'حذف',
    'Add New': 'افزودن جدید',
    'Add New Class': 'افزودن صنف جدید',
    'Add New Subject': 'افزودن مضمون جدید',
    'Add New User': 'افزودن کاربر جدید',
    'View Details': 'مشاهده جزئیات',
    View: 'مشاهده',
    Back: 'بازگشت',
    Next: 'بعدی',
    'Next Step': 'مرحله بعدی',
    'Save Record': 'ذخیره رکورد',
    'Create Record': 'ایجاد رکورد',
    'Confirm Delete': 'تأیید حذف',
    'No records found': 'رکوردی یافت نشد',
    'More Filters': 'فیلترهای بیشتر',
    Export: 'خروجی',
    'Create First Record': 'ایجاد اولین رکورد',
    'Create Flow': 'فرآیند ایجاد',
    'Edit Flow': 'فرآیند ویرایش',
    'No.': 'شماره',
    Basics: 'مبانی',
    Identity: 'هویت',
    Relations: 'روابط',
    Details: 'جزئیات',
    Review: 'بازبینی',
    'Form Error': 'خطای فرم',
    'Save error': 'خطای ذخیره‌سازی',
    'Please correct the highlighted fields.': 'لطفاً فیلدهای مشخص‌شده را اصلاح کنید.',
    Step: 'مرحله',
    'Manage income and expense transactions with live balance and verification visibility.': 'مدیریت معاملات عایدی و مصرفی با نمایش موجودی زنده و وضعیت تصدیق.',
    'Manage account balances, status, and account-type distribution.': 'مدیریت موجودی حساب‌ها، وضعیت و توزیع نوع حساب.',
    'Manage fee categories, frequencies, and active pricing structure.': 'مدیریت دسته‌بندی فیس‌ها، تکرار و ساختار قیمت‌گذاری فعال.',
    'Track fee assignments, outstanding balances, and collection risk by status.': 'پیگیری تخصیص فیس‌ها، موجودی‌های معوقه و خطر وصول بر اساس وضعیت.',
    'Manage collection activity, verification queues, and payment channels.': 'مدیریت فعالیت وصول، صف‌های تصدیق و کانال‌های پرداخت.',
    'Review spending, approval workload, and category mix from live expense records.': 'بررسی مصارف، بار کاری تصویب و ترکیب دسته‌بندی از رکوردهای زنده مصرف.',
    'Manage financial report records': 'مدیریت رکوردهای گزارش مالی',
    'Financial Transactions': 'معاملات مالی',
    'Financial Accounts': 'حساب‌های مالی',
    'Fee Structure': 'ساختار فیس',
    'Student Fees': 'فیس‌های شاگردان',
    'Fee Payments': 'پرداخت فیس',
    'Expenses': 'مصارف',
    'Date': 'تاریخ',
    'Code': 'کد',
    'Description': 'توضیحات',
    'Type': 'نوع',
    'Amount': 'مقدار',
    'Status': 'وضعیت',
    'Account Code': 'کد حساب',
    'Account Name': 'نام حساب',
    'Opening Balance': 'موجودی ابتدایی',
    'Current Balance': 'موجودی فعلی',
    'Currency': 'واحد پول',
    'Fee Code': 'کد فیس',
    'Fee Name': 'نام فیس',
    'Fee Type': 'نوع فیس',
    'Frequency': 'تکرار',
    'Mandatory': 'اجباری',
    'Student': 'شاگرد',
    'Fee Structure ID': 'آی‌دی ساختار فیس',
    'Academic Year': 'سال تحصیلی',
    'Total Amount': 'مقدار کل',
    'Discount': 'تخفیف',
    'Payable': 'قابل پرداخت',
    'Student Fee ID': 'آی‌دی فیس شاگرد',
    'Receipt No': 'شماره رسید',
    'Payment Date': 'تاریخ پرداخت',
    'Paid Amount': 'مقدار پرداختی',
    'Method': 'روش',
    'Verification': 'تصدیق',
    'Expense Code': 'کد مصرف',
    'Category': 'دسته‌بندی',
    'Title': 'عنوان',
    'Expense Date': 'تاریخ مصرف',
    'Payment Method': 'روش پرداخت',
    'Approval Status': 'وضعیت تصویب',
    'Report Type': 'نوع گزارش',
    'Report Period': 'دوره گزارش',
    'Total Income': 'عایدی کل',
    'Total Expense': 'مصرف کل',
    'Net Balance': 'موجودی خالص',
    'Transaction Type': 'نوع معامله',
    'Transaction Date': 'تاریخ معامله',
    'Reference Type': 'نوع مرجع',
    'Verification Status': 'وضعیت تصدیق',
    'Account': 'حساب',
    'Account Type': 'نوع حساب',
    'Class': 'صنف',
    'Applicable From': 'قابل اجرا از',
    'Applicable To': 'قابل اجرا تا',
    'Student Fee': 'فیس شاگرد',
    'Transaction Reference': 'مرجع معامله',
    'Payment Status': 'وضعیت پرداخت',
    'Payment Channel': 'کانال پرداخت',
    'Remarks': 'ملاحظات',
    'Reference No': 'شماره مرجع',
    'Paid To': 'پرداخت به',
    'Generated At': 'تولید شده در',
    Income: 'عاید',
    Expense: 'مصرف',
    Verified: 'تصدیق شده',
    Rejected: 'رد شده',
    Cash: 'نقد',
    'Petty Cash': 'نقد جزئی',
    Active: 'فعال',
    Inactive: 'غیرفعال',
    Tuition: 'شهریه',
    Admission: 'داخلۀ',
    'One-Time': 'یک‌باره',
    Monthly: 'ماهانه',
    Yearly: 'سالانه',
    Yes: 'بلی',
    No: 'نخیر',
    Paid: 'پرداخت شده',
    Partial: 'جزئی',
    Overdue: 'تأخیری',
    Completed: 'تکمیل شده',
    Failed: 'ناموفق',
    Approved: 'تصویب شده',
    Other: 'دیگر',
    Card: 'کارت',
    'Discount Amount': 'مقدار تخفیف',
    'Payable Amount': 'مقدار قابل پرداخت',
    'Due Date': 'تاریخ نهایی',
    'Image size must be less than 5MB': 'سایز تصویر باید کمتر از ۵MB باشد',
    'A phased entry flow keeps create and edit tasks easier to complete without overwhelming the form.': 'جریان ورود مرحله‌ای باعث می‌شود وظایف ایجاد و ویرایش آسان‌تر و بدون فشار فرم تکمیل شوند.',
    of: 'از',
    'Unknown error': 'خطای ناشناخته',
    'Delete failed': 'حذف ناموفق',
    'Delete error': 'خطای حذف',
    'Save failed': 'ذخیره ناموفق',
  },
  ps: {
    'Admin Console': 'د ادارې کنسول',
    'Admin Workspace': 'د ادارې کاري فضا',
    'Welcome back,': 'بېرته ښه راغلاست،',
    'Manage the entire institution with a cleaner workspace and faster navigation.': 'ټول موسسه د پاکې کاري فضا او چټک ناوبري سره اداره کړئ.',
    'Search modules, users, reports...': 'ماډیولونه، کاروونکي، راپورونه ولټوئ...',
    Overview: 'لنډه کتنه',
    Operations: 'عملیات',
    Management: 'اداره',
    Dashboard: 'ډشبورډ',
    'User Management': 'د کاروونکو اداره',
    'All Users': 'ټول کاروونکي',
    Students: 'زده‌کوونکي',
    Teachers: 'ښوونکي',
    Staff: 'کارکوونکي',
    'Register New User': 'نوی کاروونکی ثبت کړئ',
    'Roles & Permissions': 'نقشونه او اجازې',
    'Audit Logs': 'د پلټنې لاګونه',
    Academic: 'تعلیمي',
    Classes: 'ټولګي',
    Subjects: 'مضامین',
    Exams: 'امتحانونه',
    Timetable: 'وخت‌جدول',
    Degrees: 'درجې',
    Syllabus: 'نصاب',
    'Grading System': 'د نمرې ورکولو سیستم',
    Attendance: 'حاضري',
    'Daily Attendance': 'ورځنۍ حاضري',
    Reports: 'راپورونه',
    Settings: 'تنظیمات',
    'Attendance Warnings': 'د حاضرۍ خبرتیاوې',
    Corrections: 'اصلاحات',
    Finance: 'مالي',
    'Fee Structure': 'د فیس جوړښت',
    Payments: 'تادیات',
    Expenses: 'مصارف',
    Salaries: 'معاشونه',
    Accounts: 'حسابونه',
    Transactions: 'معاملې',
    'Financial Reports': 'مالي راپورونه',
    Library: 'کتابتون',
    Books: 'کتابونه',
    Categories: 'کټګورۍ',
    'Borrowed Books': 'پور اخیستل شوي کتابونه',
    Purchases: 'اخیستنې',
    Sales: 'پلورنې',
    Complaints: 'شکایتونه',
    'All Complaints': 'ټول شکایتونه',
    Pending: 'ځنډېدلي',
    Resolved: 'حل شوي',
    Actions: 'اقدامات',
    Feedback: 'نظر',
    Hostel: 'هاستل',
    Rooms: 'خونې',
    Allocations: 'تخصیصونه',
    Meals: 'د خوړو وختونه',
    'Meal Attendance': 'د خوړو حاضري',
    'HR Management': 'بشري سرچینې',
    Departments: 'څانګې',
    Designations: 'رتبې',
    Employees: 'کارکوونکي',
    'Employee Attendance': 'د کارکوونکو حاضري',
    'Leave Management': 'د رخصتۍ اداره',
    Payroll: 'معاش ورکول',
    'HR Reports': 'د بشري سرچینو راپورونه',
    Kitchen: 'پخلنځی',
    Inventory: 'موجودي',
    'Meal Planning': 'د خوړو پلان',
    'Weekly Menu': 'اونیزه مېنو',
    Suppliers: 'عرضه کوونکي',
    'Waste Tracking': 'د ضایعاتو تعقیب',
    'Analytics Dashboard': 'تحلیلي ډشبورډ',
    'System Settings': 'د سیستم تنظیمات',
    'General Settings': 'عمومي تنظیمات',
    'Academic Settings': 'تعلیمي تنظیمات',
    Notifications: 'خبرتیاوې',
    Security: 'امنیت',
    'Backup & Restore': 'بیک اپ او بیا رغول',
    'API Management': 'د API اداره',
    Profile: 'پروفایل',
    'Account and identity': 'حساب او هویت',
    Logout: 'وتل',
    'Exit this workspace': 'له کاري فضا څخه وتل',
    'Toggle theme': 'تم بدل کړئ',
    Language: 'ژبه',
    'Collapse sidebar': 'اړخیز پټه راټوله کړئ',
    'Expand sidebar': 'اړخیز پټه خلاصه کړئ',
    'Madrasa Info': 'د مدرسې معلومات',
    Loading: 'بارېږي',
    'Loading...': 'بارېږي...',
    Search: 'لټون',
    'Search...': 'لټون...',
    'Search And Filter': 'لټون او فلټر',
    'Quick controls for finding records faster.': 'د ریکارډونو د ژر موندلو لپاره چټک کنټرولونه.',
    'Filter By': 'فلټر پر اساس',
    'All Columns': 'ټول ستنې',
    'Filter Value': 'د فلټر ارزښت',
    'Type to filter rows...': 'د قطارونو د فلټر لپاره ولیکئ...',
    'Records Table': 'د ریکارډونو جدول',
    'Unified filtering, sorting, pagination, and row actions.': 'یو ځای فلټر، ترتیب، پاڼې او د قطار کړنې.',
    'No Records': 'ریکارډ نشته',
    'Nothing matches your current filters': 'ستاسو له اوسنیو فلټرونو سره څه نه سمون خوري',
    'Try changing the search terms, switching the filter column, or create the first record for this module.': 'د لټون کلمې بدلې کړئ، د فلټر ستنه بدله کړئ، یا د دې ماډیول لپاره لومړی ریکارډ جوړ کړئ.',
    'Unable to Load Data': 'د معلوماتو بارول ممکن نه دي',
    Retry: 'بیا هڅه',
    'Loading data...': 'معلومات بارېږي...',
    'Delete this account?': 'دا حساب ړنګ شي؟',
    'Delete this class?': 'دا ټولګی ړنګ شي؟',
    'Delete this subject?': 'دا مضمون ړنګ شي؟',
    'Delete this record?': 'دا ریکارډ ړنګ شي؟',
    'Are you sure you want to delete this record?': 'ایا ډاډه یاست چې دا ریکارډ ړنګول غواړئ؟',
    Cancel: 'لغوه',
    Save: 'ساتل',
    Create: 'جوړول',
    Update: 'تازه کول',
    Edit: 'سمول',
    Delete: 'ړنګول',
    'Add New': 'نوی اضافه کړئ',
    'Add New Class': 'نوی ټولګی اضافه کړئ',
    'Add New Subject': 'نوی مضمون اضافه کړئ',
    'Add New User': 'نوی کاروونکی اضافه کړئ',
    'View Details': 'جزئیات وګورئ',
    View: 'وګورئ',
    Back: 'شاته',
    Next: 'بل',
    'Next Step': 'بل ګام',
    'Save Record': 'ریکارډ وساتئ',
    'Create Record': 'ریکارډ جوړ کړئ',
    'Confirm Delete': 'د ړنګولو تایید',
    'No records found': 'ریکارډ ونه موندل شو',
    'More Filters': 'نور فلټرونه',
    Export: 'صادرول',
    'Create First Record': 'لومړی ریکارډ جوړ کړئ',
    'Create Flow': 'د جوړولو بهیر',
    'Edit Flow': 'د سمون بهیر',
    'No.': 'شمېره',
    Basics: 'اساسيات',
    Identity: 'هویت',
    Relations: 'اړیکې',
    Details: 'جزئیات',
    Review: 'بیاکتنه',
    'Form Error': 'د فارم تېروتنه',
    'Save error': 'د خوندي کولو تېروتنه',
    'Please correct the highlighted fields.': 'مهرباني وکړئ نښه شوي ډګرونه سم کړئ.',
    Step: 'ګام',
    'Manage income and expense transactions with live balance and verification visibility.': 'د عاید او مصرف معاملې د ژوندي بیلانس او تصدیق لید سره مدیریت کړئ.',
    'Manage account balances, status, and account-type distribution.': 'د حساب بیلانسونه، حالت او د حساب ډول توزیع مدیریت کړئ.',
    'Manage fee categories, frequencies, and active pricing structure.': 'د فیس کټګورۍ، تکرار او فعاله قیمت جوړښت مدیریت کړئ.',
    'Track fee assignments, outstanding balances, and collection risk by status.': 'د فیس تخصیصونه، پاتې بیلانسونه او د راټولولو خطر د حالت له مخې تعقیب کړئ.',
    'Manage collection activity, verification queues, and payment channels.': 'د راټولولو فعالیت، د تصدیق قطارونه او د تادیې چینلونه مدیریت کړئ.',
    'Review spending, approval workload, and category mix from live expense records.': 'د ژوندي مصرف ریکارډونو څخه لګښتونه، د تصویب کاري بار او د کټګورۍ ترکیب وڅیړئ.',
    'Manage financial report records': 'د مالي راپور ریکارډونه مدیریت کړئ.',
    'Financial Transactions': 'مالي معاملې',
    'Financial Accounts': 'مالي حسابونه',
    'Fee Structure': 'د فیس جوړښت',
    'Student Fees': 'د زده‌کوونکو فیسونه',
    'Fee Payments': 'د فیس تادیه',
    'Expenses': 'مصارف',
    'Date': 'نېټه',
    'Code': 'کوډ',
    'Description': 'تشریح',
    'Type': 'ډول',
    'Amount': 'مقدار',
    'Status': 'حالت',
    'Account Code': 'د حساب کوډ',
    'Account Name': 'د حساب نوم',
    'Opening Balance': 'پرانیستونکی بیلانس',
    'Current Balance': 'اوسنی بیلانس',
    'Currency': 'اسعار',
    'Fee Code': 'د فیس کوډ',
    'Fee Name': 'د فیس نوم',
    'Fee Type': 'د فیس ډول',
    'Frequency': 'تکرار',
    'Mandatory': 'اجباري',
    'Student': 'زده‌کوونکی',
    'Fee Structure ID': 'د فیس جوړښت آئډی',
    'Academic Year': 'تعلیمي کال',
    'Total Amount': 'ټول مقدار',
    'Discount': 'تخفیف',
    'Payable': 'د تادیې وړ',
    'Student Fee ID': 'د زده‌کوونکي فیس آئډی',
    'Receipt No': 'د رسید شمېره',
    'Payment Date': 'د تادیې نېټه',
    'Paid Amount': 'تادیه شوی مقدار',
    'Method': 'طریقه',
    'Verification': 'تصدیق',
    'Expense Code': 'د مصرف کوډ',
    'Category': 'کټګوري',
    'Title': 'سرلیک',
    'Expense Date': 'د مصرف نېټه',
    'Payment Method': 'د تادیې طریقه',
    'Approval Status': 'د تصویب حالت',
    'Report Type': 'د راپور ډول',
    'Report Period': 'د راپور دوره',
    'Total Income': 'ټول عاید',
    'Total Expense': 'ټول مصرف',
    'Net Balance': 'خالص بیلانس',
    'Transaction Type': 'د معاملې ډول',
    'Transaction Date': 'د معاملې نېټه',
    'Reference Type': 'د حوالې ډول',
    'Verification Status': 'د تصدیق حالت',
    'Account': 'حساب',
    'Account Type': 'د حساب ډول',
    'Class': 'ټولګی',
    'Applicable From': 'له ... څخه پلي',
    'Applicable To': 'تر ... پورې پلي',
    'Student Fee': 'د زده‌کوونکي فیس',
    'Transaction Reference': 'د معاملې حواله',
    'Payment Status': 'د تادیې حالت',
    'Payment Channel': 'د تادیې چینل',
    'Remarks': 'ملاحظات',
    'Reference No': 'د حوالې شمېره',
    'Paid To': 'تادیه شوی',
    'Generated At': 'په ... کې رامینځته شوی',
    Income: 'عاید',
    Expense: 'مصرف',
    Verified: 'تصدیق شوی',
    Rejected: 'رد شوی',
    Cash: 'نقد',
    'Petty Cash': 'نقد کوچنی',
    Active: 'فعال',
    Inactive: 'غیرفعال',
    Tuition: 'سبق',
    Admission: 'داخلې',
    'One-Time': 'یو ځل',
    Monthly: 'میاشتنی',
    Yearly: 'کلنی',
    Yes: 'هو',
    No: 'نه',
    Paid: 'تادیه شوی',
    Partial: 'برخه ییز',
    Overdue: 'تأخیر شوی',
    Completed: 'بشپړ شوی',
    Failed: 'نابریالی',
    Approved: 'تصویب شوی',
    Other: 'نور',
    Card: 'کارت',
    'Discount Amount': 'د تخفیف اندازه',
    'Payable Amount': 'د تادیې وړ اندازه',
    'Due Date': 'وروستۍ نېټه',
    'Image size must be less than 5MB': 'د انځور اندازه باید له ۵MB څخه کمه وي',
    'A phased entry flow keeps create and edit tasks easier to complete without overwhelming the form.': 'د مرحله‌ییز ننوتلو بهیر د جوړولو او سمولو دندې د فارم له فشار پرته اسانه کوي.',
    of: 'د',
    'Unknown error': 'نامعلومه تېروتنه',
    'Delete failed': 'ړنګول نابریالی',
    'Delete error': 'د ړنګولو تېروتنه',
    'Save failed': 'خوندي کول نابریالی',
  },
};

export const getAdminLocale = (lang = 'en') => ADMIN_TEXT_MAP[lang] ? lang : 'en';

export const localizeAdminText = (text, lang = 'en') => {
  if (text === null || text === undefined) return text;
  if (typeof text !== 'string') return text;
  const key = text.trim();
  if (!key) return text;
  const locale = getAdminLocale(lang);
  return ADMIN_TEXT_MAP[locale]?.[key] || text;
};

export const translateAdminTree = (root, lang = 'en') => {
  if (!root) return;
  const locale = getAdminLocale(lang);
  const walk = (node) => {
    if (!node || node.nodeType !== Node.ELEMENT_NODE) return;
    if (node.closest?.('[data-no-admin-translate="true"]')) return;

    if (node.tagName === 'OPTION' && node.value !== '') {
      const translated = localizeAdminText(node.textContent, locale);
      if (translated !== node.textContent) node.textContent = translated;
    }

    for (const attr of ['title', 'placeholder', 'aria-label']) {
      const value = node.getAttribute?.(attr);
      if (value) {
        const translated = localizeAdminText(value, locale);
        if (translated !== value) node.setAttribute(attr, translated);
      }
    }

    const walker = document.createTreeWalker(node, NodeFilter.SHOW_TEXT);
    let current = walker.nextNode();
    while (current) {
      const translated = localizeAdminText(current.nodeValue, locale);
      if (translated !== current.nodeValue) {
        current.nodeValue = translated;
      }
      current = walker.nextNode();
    }
  };

  walk(root);
};

export default ADMIN_TEXT_MAP;
